# syntax=docker/dockerfile:1

FROM golang:1.16-alpine AS base
WORKDIR /app
ENV CGO_ENABLED=0
COPY go.* .
RUN go mod download
COPY . .

FROM base AS unit-test
RUN go test -v .

FROM base AS build
RUN cd ./main && go build -o /urlshortner

FROM gcr.io/distroless/base-debian10
ENV HTTP_PORT=8080
WORKDIR /
COPY --from=build /urlshortner /urlshortner
EXPOSE 8080
ENTRYPOINT ["/urlshortner"]